pkp/pkp-lib#6251 Add isPreprintOf relation to DOI exports
pkp/crossref-ops pull request #10
Opened 2022-02-26 19:51 UTC by ajnyga

https://github.com/pkp/pkp-lib/issues/6251

2022-02-26 19:58 UTC, ajnyga commented
@ewhanson @NateWr 

This is an additional change to the OPS Crossref plugin to introduce isPreprintOf relation (link to the version of record DOI).

There is an older pr for this, but it was delayed because of the ongoing DOI work. See the discussion here where Nate suggest how the OPS DOI plugin should force versioning of DOIs if Crossref is used for registering: https://github.com/pkp/ops/pull/103/files. However, now I've just heard from Alex that this could change. But that is probably something that still needs to be resolved.

In any case this should be merged first, I can rebase this pr after that if needed: https://github.com/pkp/crossref-ops/pull/9

2022-03-21 11:52 UTC, NateWr requested changes
Looks good. Just the one change to code organisation.

2022-03-21 11:52 UTC, NateWr commented on filter/PreprintCrossrefXmlFilter.inc.php
> +    public function createRelationsDataNode($doc, $parentDoi, $vorDoi)
Can you split this into two methods: `createParentDoiNode()` and `createVorDoiNode()`?

2022-03-23 07:18 UTC, ajnyga commented on filter/PreprintCrossrefXmlFilter.inc.php
> +    public function createRelationsDataNode($doc, $parentDoi, $vorDoi)
Are you thinking that those would be called inside `createRelationsDataNode` or inside `createPostedContentNode`?

2022-03-23 09:10 UTC, NateWr commented on filter/PreprintCrossrefXmlFilter.inc.php
> +    public function createRelationsDataNode($doc, $parentDoi, $vorDoi)
Inside `createPostedContentNode`

2022-05-22 17:51 UTC, ajnyga commented
@NateWr split the function to two parts as requested.

Since https://github.com/pkp/crossref-ops/pull/9 is touching the same code, I will wait for this to be merged first.

2022-05-26 10:40 UTC, NateWr approved these changes

2022-05-26 10:40 UTC, NateWr commented
Looks good. Are there any other pull requests that need to be merged simultaneously with this one?

2022-06-13 18:17 UTC, ajnyga commented
hmm, why did I not see an alert about this...

There is another one, but it would be easier if this would be merged first and I could rebase the other and pr it then.

2022-06-20 15:39 UTC, merged