pkp/pkp-lib#7222 Use default landing page url for current publication
pkp/crossref-ops pull request #9
Opened 2022-02-25 16:05 UTC by ajnyga

https://github.com/pkp/pkp-lib/issues/7222

2022-02-26 06:12 UTC, ajnyga commented
oh, noticed I need a continue instead of break there. Will fix that.

2022-03-10 16:15 UTC, asmecher commented
Nate, I think you're already active on this one.

2022-03-21 12:10 UTC, NateWr requested changes

2022-03-21 12:10 UTC, NateWr commented on filter/PreprintCrossrefXmlFilter.inc.php
> +            $postedContentNode->appendChild($this->createRelationsDataNode($doc, $submission->getCurrentPublication()->getDoi()));
Does this overlap with your other PR regarding VOR?

2022-03-21 12:10 UTC, NateWr commented on filter/PreprintCrossrefXmlFilter.inc.php
> +
I struggled to understand all of the conditional logic from lines 76-99. Can I suggest an alternate approach where you always add a node for the current publication, and then add additional nodes for other publications when they have a different DOI? Like this:

```php
$postedContentNode = $this->createPostedContentNode($doc, $pubObject->getCurrentPublication(), $pubObject);
$bodyNode->appendChild($postedContentNode);
$publications = array_reverse($pubObject->getPublishedPublications());
foreach ($publications as $publication) {
    if ($publication->getDoi() && $publication->getDoi() !== $pubObject->getCurrentPublication()->getDoi()) {
        $postedContentNode = $this->createPostedContentNode($doc, $publication, $pubObject);
        $bodyNode->appendChild($postedContentNode);
    }
}
```

Would that achieve the same thing?

2022-03-23 06:59 UTC, ajnyga commented on filter/PreprintCrossrefXmlFilter.inc.php
> +            $postedContentNode->appendChild($this->createRelationsDataNode($doc, $submission->getCurrentPublication()->getDoi()));
Yes, they touche the same place. Have to merge the other one first and then make sure there are no conflicts.

2022-03-23 07:16 UTC, ajnyga commented on filter/PreprintCrossrefXmlFilter.inc.php
> +
I am sure I had something in my mind when you went on splitting this to two loops, but can not understand anymore what I was thinking. Yes this should work. The idea is to have one node if the DOI is the same (meaning that we just update the metadata) and several nodes if the DOI changes between versions.

2022-07-04 10:18 UTC, NateWr requested changes

2022-07-04 10:18 UTC, NateWr commented on filter/PreprintCrossrefXmlFilter.inc.php
> +            $url = $dispatcher->url($request, Application::ROUTE_PAGE, null, 'preprint', 'view', [$submission->getBestId(), 'version', $publication->getId()], null, null, true);
I'm not sure but this might break when the code is run as part of an API request (which might be the case with the new changes). The reason is that when specifying a route type (`Application::ROUTE_PAGE`) that doesn't match the current request, I think it requires a context path to be passed.

It looks like you've already got a `$context` in this method, so you should be able to replace the `null` right after `ROUTE_PAGE` with `$context->getPath()`. But you might want to test it first.

2022-07-18 09:27 UTC, NateWr commented
Yeah let's see what happens in the discussion for https://github.com/pkp/pkp-lib/issues/8027.

2022-08-07 17:44 UTC, ajnyga commented
Did you make a decision about the versioning?

2022-08-08 09:48 UTC, NateWr commented
Yes, we decided to remove the feature to automatically generate a new DOI for each version. I believe support for the `%b` variable has just been removed.

2022-08-10 11:12 UTC, ajnyga commented
ok, so basically in that case we just want to have
`$postedContentNode = $this->createPostedContentNode($doc, $pubObject->getCurrentPublication(), $pubObject);`
and no looping through other versions. Also we can remove the intraWork relations that deal with versions.

Right?

2022-08-10 11:30 UTC, NateWr commented
@ajnyga I'm not sure. It's still possible to assign different DOIs to two versions of the same publication. The only thing we settled on was removing the automatic creation of a different DOI for each version.

2025-02-22 17:26 UTC, closed without merging